export type MerchantStatus = "active" | "paused" | "blocked";
export type RiskLevel = "low" | "medium" | "high";

export interface MonthlyData {
    month: string;
    volume: number;
    successRate: number;
    transactions: number;
}

export interface Merchant {
    id: string;
    name: string;
    country: string;
    status: MerchantStatus;
    monthlyVolume: number;
    chargebackRatio: number;
    riskLevel: RiskLevel;
    // Fields for dashboard charts
    volume: number;
    successRate: number;
    transactions: number;
    lastActivity: string;
    monthlyData: MonthlyData[];
}

const generateMonthlyData = (
    baseVolume: number,
    baseSuccessRate: number,
    baseTransactions: number
): MonthlyData[] => {
    const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"];
    return months.map((month) => {
        const variation = (Math.random() - 0.5) * 0.3; // ±15% variation
        const volumeVariation = (Math.random() - 0.5) * 0.2; // ±10% variation
        const transactionVariation = (Math.random() - 0.5) * 0.15; // ±7.5% variation

        return {
            month,
            volume: Math.round(baseVolume * (1 + volumeVariation)),
            successRate: Math.round((baseSuccessRate * (1 + variation)) * 10) / 10,
            transactions: Math.round(baseTransactions * (1 + transactionVariation)),
        };
    });
};

export const merchants: Merchant[] = [
    {
        id: "1",
        name: "TechCorp Solutions",
        country: "United States",
        status: "active",
        monthlyVolume: 1250000,
        chargebackRatio: 0.8,
        riskLevel: "low",
        volume: 125000,
        successRate: 96.5,
        transactions: 1245,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(125000, 96.5, 1245),
    },
    {
        id: "2",
        name: "RetailMax Inc",
        country: "United Kingdom",
        status: "active",
        monthlyVolume: 890000,
        chargebackRatio: 1.2,
        riskLevel: "low",
        volume: 89000,
        successRate: 94.2,
        transactions: 892,
        lastActivity: "2024-01-14",
        monthlyData: generateMonthlyData(89000, 94.2, 892),
    },
    {
        id: "3",
        name: "GlobalTrade Ltd",
        country: "Germany",
        status: "active",
        monthlyVolume: 1560000,
        chargebackRatio: 0.5,
        riskLevel: "low",
        volume: 156000,
        successRate: 97.8,
        transactions: 1567,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(156000, 97.8, 1567),
    },
    {
        id: "4",
        name: "DigitalStore Co",
        country: "Canada",
        status: "paused",
        monthlyVolume: 670000,
        chargebackRatio: 2.1,
        riskLevel: "medium",
        volume: 67000,
        successRate: 92.1,
        transactions: 678,
        lastActivity: "2024-01-13",
        monthlyData: generateMonthlyData(67000, 92.1, 678),
    },
    {
        id: "5",
        name: "Ecommerce Pro",
        country: "Australia",
        status: "active",
        monthlyVolume: 2340000,
        chargebackRatio: 0.9,
        riskLevel: "low",
        volume: 234000,
        successRate: 95.6,
        transactions: 2345,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(234000, 95.6, 2345),
    },
    {
        id: "6",
        name: "MarketPlace Hub",
        country: "France",
        status: "active",
        monthlyVolume: 1890000,
        chargebackRatio: 1.5,
        riskLevel: "medium",
        volume: 189000,
        successRate: 93.4,
        transactions: 1890,
        lastActivity: "2024-01-14",
        monthlyData: generateMonthlyData(189000, 93.4, 1890),
    },
    {
        id: "7",
        name: "ShopOnline Now",
        country: "Japan",
        status: "active",
        monthlyVolume: 1120000,
        chargebackRatio: 1.8,
        riskLevel: "medium",
        volume: 112000,
        successRate: 91.8,
        transactions: 1123,
        lastActivity: "2024-01-12",
        monthlyData: generateMonthlyData(112000, 91.8, 1123),
    },
    {
        id: "8",
        name: "TradeConnect",
        country: "Singapore",
        status: "active",
        monthlyVolume: 1450000,
        chargebackRatio: 0.6,
        riskLevel: "low",
        volume: 145000,
        successRate: 96.9,
        transactions: 1456,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(145000, 96.9, 1456),
    },
    {
        id: "9",
        name: "Inactive Merchant",
        country: "Brazil",
        status: "blocked",
        monthlyVolume: 450000,
        chargebackRatio: 4.5,
        riskLevel: "high",
        volume: 45000,
        successRate: 88.5,
        transactions: 450,
        lastActivity: "2024-01-05",
        monthlyData: generateMonthlyData(45000, 88.5, 450),
    },
    {
        id: "10",
        name: "QuickBuy Store",
        country: "India",
        status: "active",
        monthlyVolume: 980000,
        chargebackRatio: 1.1,
        riskLevel: "low",
        volume: 98000,
        successRate: 94.7,
        transactions: 987,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(98000, 94.7, 987),
    },
    {
        id: "11",
        name: "FastPay Services",
        country: "Spain",
        status: "active",
        monthlyVolume: 1320000,
        chargebackRatio: 0.7,
        riskLevel: "low",
        volume: 132000,
        successRate: 95.2,
        transactions: 1320,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(132000, 95.2, 1320),
    },
    {
        id: "12",
        name: "SecureTrade Global",
        country: "Netherlands",
        status: "paused",
        monthlyVolume: 760000,
        chargebackRatio: 2.8,
        riskLevel: "high",
        volume: 76000,
        successRate: 90.3,
        transactions: 760,
        lastActivity: "2024-01-10",
        monthlyData: generateMonthlyData(76000, 90.3, 760),
    },
    {
        id: "13",
        name: "PrimeCommerce",
        country: "Sweden",
        status: "active",
        monthlyVolume: 2100000,
        chargebackRatio: 0.4,
        riskLevel: "low",
        volume: 210000,
        successRate: 98.1,
        transactions: 2100,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(210000, 98.1, 2100),
    },
    {
        id: "14",
        name: "ValueMart",
        country: "Italy",
        status: "active",
        monthlyVolume: 1100000,
        chargebackRatio: 1.9,
        riskLevel: "medium",
        volume: 110000,
        successRate: 93.7,
        transactions: 1100,
        lastActivity: "2024-01-14",
        monthlyData: generateMonthlyData(110000, 93.7, 1100),
    },
    {
        id: "15",
        name: "EliteRetail",
        country: "Switzerland",
        status: "active",
        monthlyVolume: 1750000,
        chargebackRatio: 0.9,
        riskLevel: "low",
        volume: 175000,
        successRate: 96.2,
        transactions: 1750,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(175000, 96.2, 1750),
    },
    {
        id: "16",
        name: "SmartShop",
        country: "South Korea",
        status: "blocked",
        monthlyVolume: 320000,
        chargebackRatio: 5.2,
        riskLevel: "high",
        volume: 32000,
        successRate: 85.4,
        transactions: 320,
        lastActivity: "2024-01-03",
        monthlyData: generateMonthlyData(32000, 85.4, 320),
    },
    {
        id: "17",
        name: "GlobalBuy",
        country: "Mexico",
        status: "active",
        monthlyVolume: 880000,
        chargebackRatio: 1.3,
        riskLevel: "low",
        volume: 88000,
        successRate: 94.8,
        transactions: 880,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(88000, 94.8, 880),
    },
    {
        id: "18",
        name: "TradeHub",
        country: "Poland",
        status: "paused",
        monthlyVolume: 540000,
        chargebackRatio: 3.1,
        riskLevel: "high",
        volume: 54000,
        successRate: 89.2,
        transactions: 540,
        lastActivity: "2024-01-08",
        monthlyData: generateMonthlyData(54000, 89.2, 540),
    },
    {
        id: "19",
        name: "PremiumStore",
        country: "United Arab Emirates",
        status: "active",
        monthlyVolume: 1980000,
        chargebackRatio: 0.8,
        riskLevel: "low",
        volume: 198000,
        successRate: 97.3,
        transactions: 1980,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(198000, 97.3, 1980),
    },
    {
        id: "20",
        name: "ExpressPay",
        country: "New Zealand",
        status: "active",
        monthlyVolume: 920000,
        chargebackRatio: 1.0,
        riskLevel: "low",
        volume: 92000,
        successRate: 95.1,
        transactions: 920,
        lastActivity: "2024-01-15",
        monthlyData: generateMonthlyData(92000, 95.1, 920),
    },
];
